version: "3"

services:
  appsmith:
    build: 
      context: .
    ports:
      - ${APPSMITH_HOST_HTTP_PORT}:80
    volumes:
      # - stacks:/appsmith_stacks
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_APPSMITH}
    restart: unless-stopped
volumes:
  stacks: