# version: "3"
# services:
#   appsmith:
#     build:
#       context: .
#     container_name: appsmith
#     ports:
#       - "${APPSMITH_HOST_HTTP_PORT}:80"
#       - "443:443"
#     volumes:
#       - ${APP_CODE_PATH_HOST}:/appsmith-stacks

version: "3"

services:
  appsmith:
    build: 
      context: .
    ports:
      - ${APPSMITH_HOST_HTTP_PORT}:80
    volumes:
      - stacks:/appsmith_stacks
      # - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_APPSMITH}${APP_CODE_CONTAINER_FLAG}'
    restart: unless-stopped
volumes:
  stacks: